### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by superbonaci** [nanaian/papermario-dx#20]
Without a license mods can't be made, nor any modification of derivative work.

**Comment by nanaian** [comment]
I don't intend to license this work yet, partially because upstream lacks a license (https://github.com/pmret/papermario/issues/1024). I'm working on an update/different tool that enables mods be licensed. If you have any further questions feel free to message me on Discord: nanaian on [Paper Mario Modding](https://discord.gg/paper-mario-modding-279322074412089344) or email `alex` at my username `.town`
